# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Slide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI'
  
  # Facebook
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  # Google
  pod 'GoogleSignIn'
  
  # temporary solution to warnings
  pod 'Protobuf', :inhibit_warnings => true

end
 
